openapi: '3.0.2'
info:
  title: Logistics Apps API
  description: 
    Simple Logistics API for exercise
  version: '1.0.1'
  contact:
    name: Lukmanul Khakim
    email: klukmanul33@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers: #lokasi layanan dapat diakses
  - url: localhost:8000

tags: #segmen
  - name: user
    description: managemen data user
  - name: vendor
    description: managemen vendor pengirim
  - name: expedisi
    description: managemen transaksi dengan vendor

paths:
  /vendor:
    get:
      security:
        - VendorAuth : []
          
      summary: "show all vendor"
      tags:
        - "vendor"
      parameters:
        - name: J_expedisi
          in: query
          description: "Filter by Jalur Expedisi(darat/laut/udara)"
          required: false
          schema :
            type: string
          examples:
            darat:
              description: "example vendor exp darat"
              value : "darat"
            laut:
              description: "example vendor exp laut"
              value : "laut"
            udara :
              description: "example vendor exp udara"
              value: "udara"
        - name: is_done
          in : query
          description: "filter by expedisi is_done"
          required: false
          schema :
            type: boolean
            nullable: true
            default : true
      responses:
        '200':
          description: "berhasil mengambil seluruh data vendor order"
          content:
            application/json:
              schema:
                $ref : "#/components/schemas/ArrayVendorObj"       
        '500':
          $ref: "#components/responses/500"
     

    post :
      security:
        - VendorAuth : []
      summary: "Add data logistics order"
      tags:
        - "vendor"
      requestBody :
        required: true
        content:
          "application/json":
            schema:
              $ref : "#/components/schemas/vendorObj"   

      responses:
        '201':
          description: "Add new expedition"
          content:
            application/json:
              schema :
                type: object
                $ref : "#/components/schemas/vendorResSucses"
              
        '500':
          $ref : "#/components/responses/500"


        


components:
  securitySchemes:
    "VendorAuth" :
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    '500':
      description: "Server eror"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: "server eror,cant get data" 
    '201':
      description: "sucses add new expedisi"
      content:
        application/json:
          schema: 
            type: object
            properties:
              message:
                type: string
              data :
                type: object    
  schemas:
    "vendorObj":
      type: object
      properties:
        "id":
          type: integer
          format: int64
        "nama pj":
          type: string
        "transport":
          type: string
        "J_expedisi":
          type: string
        "tgl_kirim":
          type: string
          format: date
        "tgl_sampai":
          type: string
          format: date
        "is_done":
          type: boolean
          default: true
      example:
        id: 1
        nama_pj: "Bondan"
        transport: "Truck"
        J_expedisi: "darat"
        tgl_kirim: "2022-09-22"
        tgl_sampai: "2022-10-03"
        is_done : true 
        
    "vendorResSucses":
      type: object
      properties:
        message: 
          type: string
        data :
          type: object
      example : 
        id: 1
        nama_pj: "Bondan"
        transport: "Truck"
        J_expedisi: "darat"
        tgl_kirim: "2022-09-22"
        tgl_sampai: "2022-10-03"
        is_done : true 
        
    "ArrayVendorObj":
      type: array
      items :
        $ref: "#/components/schemas/vendorObj"      
    

      
    

  



          
            
